//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_ButtonMode_from_RESET(void);
extern void enter_FlashMode_from_ButtonMode(void);
extern void enter_ButtonMode_from_FlashMode(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void WDT_0_enter_ButtonMode_from_RESET(void);
extern void VREG_0_enter_ButtonMode_from_RESET(void);
extern void PORTS_0_enter_ButtonMode_from_RESET(void);
extern void PORTS_1_enter_ButtonMode_from_RESET(void);
extern void PORTS_2_enter_ButtonMode_from_RESET(void);
extern void PORTS_3_enter_ButtonMode_from_RESET(void);
extern void PBCFG_0_enter_ButtonMode_from_RESET(void);
extern void CIP51_0_enter_ButtonMode_from_RESET(void);
extern void CLOCK_0_enter_ButtonMode_from_RESET(void);
extern void TIMER16_2_enter_ButtonMode_from_RESET(void);
extern void SPI_0_enter_ButtonMode_from_RESET(void);
extern void INTERRUPT_0_enter_ButtonMode_from_RESET(void);
extern void USBLIB_0_enter_ButtonMode_from_RESET(void);
extern void PORTS_0_enter_FlashMode_from_ButtonMode(void);
extern void PBCFG_0_enter_FlashMode_from_ButtonMode(void);
extern void SPI_0_enter_FlashMode_from_ButtonMode(void);
extern void PORTS_0_enter_ButtonMode_from_FlashMode(void);
extern void PBCFG_0_enter_ButtonMode_from_FlashMode(void);
extern void SPI_0_enter_ButtonMode_from_FlashMode(void);
// [Config(Per-Module Mode)Transition Prototypes]$

#endif

